/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UjrClock {
    'format': string;
  }
  interface UjrClockAttributes extends StencilHTMLAttributes {
    'format'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UjrClock': Components.UjrClock;
  }

  interface StencilIntrinsicElements {
    'ujr-clock': Components.UjrClockAttributes;
  }


  interface HTMLUjrClockElement extends Components.UjrClock, HTMLStencilElement {}
  var HTMLUjrClockElement: {
    prototype: HTMLUjrClockElement;
    new (): HTMLUjrClockElement;
  };

  interface HTMLElementTagNameMap {
    'ujr-clock': HTMLUjrClockElement
  }

  interface ElementTagNameMap {
    'ujr-clock': HTMLUjrClockElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
